# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('subject', models.CharField(max_length=140, verbose_name='Subject')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'documents/message/files/%Y/%m/%d', verbose_name='File')),
                ('message_read', models.BooleanField(default=False, verbose_name='Message Read')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last modification')),
            ],
            options={
                'ordering': ['-last_modified'],
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MessageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_manager_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'MessageManager',
                'verbose_name_plural': 'MessagesManager',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'documents/message/files/%Y/%m/%d', verbose_name='File')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last modification')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='inbox.Message', verbose_name='Message')),
                ('message_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_message_send', to='inbox.MessageManager', verbose_name='User')),
            ],
            options={
                'ordering': ['last_modified'],
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='message_manager_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_manager_response', to='inbox.MessageManager', verbose_name='To'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_manager_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_manager_request', to='inbox.MessageManager', verbose_name='From'),
        ),
    ]
