# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemanager',
            options={'ordering': ['user'], 'verbose_name': 'Message Manager', 'verbose_name_plural': 'Messages Manager'},
        ),
    ]
