# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170118_2227'),
        ('submission', '0003_auto_20170121_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='collections',
        ),
        migrations.AddField(
            model_name='event',
            name='collections',
            field=models.ManyToManyField(to='manager.Collection', verbose_name='Collections'),
        ),
    ]
