# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20170121_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': (('list_submission_to_review', 'List Submission To  Review'), ('detail_submission_to_review', 'Detail Submission To Review'), ('submit_final', 'Submit Final')), 'verbose_name': 'Submission', 'verbose_name_plural': 'Submission'},
        ),
    ]
