from account_view import UserCreate
from reviser_view import ReviserListView, ReviserCreateView, ReviserDeleteView
from administrator_view import AdministratorListView, AdministratorCreateView, AdministratorDeleteView
from participant_view import ParticipantListView