# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, help_text='Please enter you first name.', max_length=100, null=True, verbose_name='First Name ')),
                ('last_name', models.CharField(blank=True, help_text='Please enter you last name.', max_length=100, null=True, verbose_name='Last Name ')),
                ('username', models.CharField(help_text='Please enter you username.', max_length=254, unique=True, verbose_name='Username')),
                ('email', models.EmailField(help_text='Please enter you email.', max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Moderator Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_reviser', models.BooleanField(default=False, verbose_name='Reviser Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'permissions': (('list_participant', 'List Participant'), ('list_reviser', 'List Reviser'), ('add_reviser', 'Add Reviser'), ('change_reviser', 'Change Reviser'), ('delete_reviser', 'Delete Reviser'), ('list_administrator', 'List Administrator'), ('add_administrator', 'Add Administrator'), ('delete_administrator', 'Delete Administrator')),
            },
        ),
    ]
