from event_view import EventListView, EventCreateView, EventUpdateView, EventDeleteView, EventDetailView
from submission_view import SubmissionListView, SubmissionsToReviewListView, SubmissionCreateView, SubmissionUpdateView, SubmissionDeleteView, SubmissionDetailView, SubmissionChangeReviser, SubmissionToReviewDetailView, SubmissionSubmitFinal, SubmissionFinalListView
from review_view import ReviewCreateView, ReviewUpdateView, ReviewDeleteView, ReviewDetailView
from report_view import ReportSubmissionView