# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference name')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('acronym', models.CharField(max_length=100, verbose_name='Acronym')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=1000, unique=True, verbose_name='slug')),
                ('typology', models.CharField(choices=[('article', 'Article'), ('book', 'Book'), ('booklet', 'Booklet'), ('conference', 'Conference'), ('inbook', 'Inbook'), ('incollection', 'Incollection'), ('manual', 'Manual'), ('mastersthesis', 'Masters Thesis'), ('monography', 'Monography'), ('dissertation', 'Dissertation'), ('abstract', 'Abstract')], max_length=100, verbose_name='Typology')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('reference', models.CharField(max_length=1000, verbose_name='Reference')),
                ('uri', models.URLField(max_length=500, verbose_name='URI')),
                ('language', models.CharField(choices=[('pt_BR', 'Brazilian Portuguese'), ('en', 'English'), ('es', 'Spanish')], max_length=100, verbose_name='Language')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('other_abstract', models.TextField(blank=True, null=True, verbose_name='Other Abstract')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('file', models.FileField(upload_to=b'documents/publication/%Y/%m/%d', verbose_name='File')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('is_final', models.BooleanField(default=False, verbose_name='Is Final')),
                ('authors', models.ManyToManyField(related_name='Authors', to='manager.Author', verbose_name='Authors')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Collection', verbose_name='Collection')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Community', verbose_name='Community')),
                ('keywords', models.ManyToManyField(related_name='Keywords', to='manager.Keyword', verbose_name='Keywords')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'ordering': ['-registration_date'],
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='publication',
            name='subjects',
            field=models.ManyToManyField(to='manager.Subject', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='collection',
            name='communities',
            field=models.ManyToManyField(to='manager.Community', verbose_name='Communities'),
        ),
    ]
