# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170118_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='principal_keywords',
            field=models.ManyToManyField(blank=True, null=True, related_name='principal_keywords', to='manager.Keyword', verbose_name='Principal Keywords'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='principal_language',
            field=models.CharField(blank=True, choices=[('pt_BR', 'Brazilian Portuguese'), ('en', 'English'), ('es', 'Spanish')], max_length=100, null=True, verbose_name='Principal Language'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='secondary_keywords',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondary_keywords', to='manager.Keyword', verbose_name='Secondary Keywords'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='secondary_language',
            field=models.CharField(blank=True, choices=[('pt_BR', 'Brazilian Portuguese'), ('en', 'English'), ('es', 'Spanish')], max_length=100, null=True, verbose_name='Secondary Language'),
        ),
    ]
