# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170118_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='principal_keywords',
            field=models.ManyToManyField(blank=True, related_name='principal_keywords', to='manager.Keyword', verbose_name='Principal Keywords'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='secondary_keywords',
            field=models.ManyToManyField(blank=True, related_name='secondary_keywords', to='manager.Keyword', verbose_name='Secondary Keywords'),
        ),
    ]
